"""
Export Service
===============
Generates downloadable JSON and PDF exports from form submissions.
Uses ReportLab for PDF generation — no external services needed.
"""

import json
import os
from datetime import datetime
from io import BytesIO
from typing import Dict, Any

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.enums import TA_CENTER

from app.core.config import settings


def export_json(form_data: Dict[str, Any], submission_id: int) -> bytes:
    """Serialize form submission to pretty-printed JSON bytes."""
    payload = {
        "submission_id": submission_id,
        "exported_at": datetime.utcnow().isoformat() + "Z",
        "form_data": form_data,
    }
    return json.dumps(payload, indent=2, ensure_ascii=False).encode("utf-8")


def export_pdf(form_data: Dict[str, Any], submission_id: int) -> bytes:
    """
    Generate a formatted PDF report from the form submission.
    Returns raw PDF bytes ready to stream to the client.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2 * cm,
        title=f"Form Submission #{submission_id}",
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=20,
        textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=6,
        alignment=TA_CENTER,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#6b7280"),
        alignment=TA_CENTER,
        spaceAfter=24,
    )
    label_style = ParagraphStyle(
        "Label",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.HexColor("#6b7280"),
        fontName="Helvetica-Bold",
        spaceBefore=4,
    )
    value_style = ParagraphStyle(
        "Value",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#111827"),
        spaceBefore=2,
        spaceAfter=8,
    )

    story = []

    # ── Header ────────────────────────────────────────────────────────────
    story.append(Paragraph("AI Form Filler", title_style))
    story.append(Paragraph(
        f"Submission #{submission_id} · {datetime.utcnow().strftime('%B %d, %Y')}",
        subtitle_style
    ))

    # ── Divider line ──────────────────────────────────────────────────────
    story.append(Table(
        [[""]],
        colWidths=["100%"],
        style=TableStyle([
            ("LINEBELOW", (0, 0), (-1, -1), 1.5, colors.HexColor("#e5e7eb")),
        ]),
    ))
    story.append(Spacer(1, 16))

    # ── Form Fields ───────────────────────────────────────────────────────
    LABELS = {
        "full_name":      "Full Name",
        "date_of_birth":  "Date of Birth",
        "email":          "Email Address",
        "phone":          "Phone Number",
        "address":        "Home Address",
        "id_number":      "ID / Passport Number",
        "nationality":    "Nationality",
        "employer":       "Employer",
        "position":       "Job Title",
        "monthly_income": "Monthly Income",
        "civil_status":   "Civil Status",
    }

    for key, label in LABELS.items():
        value = form_data.get(key)
        if value:
            story.append(Paragraph(label.upper(), label_style))
            story.append(Paragraph(str(value), value_style))

    # ── Footer ────────────────────────────────────────────────────────────
    story.append(Spacer(1, 32))
    story.append(Table(
        [[""]],
        colWidths=["100%"],
        style=TableStyle([
            ("LINEABOVE", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
        ]),
    ))
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        "Generated by AI Auto Form Filler",
        ParagraphStyle(
            "Footer",
            parent=styles["Normal"],
            fontSize=8,
            textColor=colors.HexColor("#9ca3af"),
            alignment=TA_CENTER,
        ),
    ))

    doc.build(story)
    return buffer.getvalue()
